app = "puzzeltochtmaastricht"
primary_region = "ams"

[build]
builder = "heroku/buildpacks:20"  # Gebruik de buildpack voor statische sites

[http_service]
internal_port = 8080  # Fly.io zal automatisch je site bedienen
force_https = true    # Zorg ervoor dat HTTPS altijd wordt gebruikt
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
memory_mb = 1024
