app = "code-maastricht"

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = ["heroku/nodejs"]
  args = { }

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[experimental]
  cmd = "npm start"
  auto_rollback = true

[mounts]
  source = "pushserver"
  destination = "/app"
